### ISSUE TITLE
Issues with Storing and Searching Notes

### ISSUE THREAD

**Issue by javiertoledo** [theam/eLLMental-kt#38]
While running the sample eLLMental project, when "search" is run after storing notes, it only retrieves the IDs of the Pinecone vectors instead of the actual notes.

Furthermore, there is a problem in the search functionality itself. For instance, regardless of the content of the search (e.g., "test" or "hello"), it always retrieves 2 vectors.

**Comment by NickSeagull** [comment]
This has been solved in #35
